### ISSUE TITLE
Icons to make more responsive

### ISSUE THREAD

**Issue by Bhavya-22** [enviroCar/enviroCar-app#662] opened 2021-03-23 14:25 UTC
**Issue** :- When bluetooth, OBD, GPS, Car are off or on red then on click the icons the respective button to on are directed but when they are blue on click nothing will happen.

**How will I fix this** :- When icons are blue i will make a toast message with icon focusable so that icon will be seen responsive and on click icon respective toast message will be seen. Like on click bluetooth icon  the toast message will be "Device's Bluetooth is on". 

**I will be working on this issue**

**Comment by asaikarthikeya** [comment] 2021-03-23 14:32
Duplicate #611

**Comment by Bhavya-22** [comment] 2021-03-23 14:37
@asaikarthikeya  @ritish099 trying to make it off again on click I am trying to show the meaning of that blue icon again on click.
Its different from #611.
Hope you got my point.

**Comment by Bhavya-22** [comment] 2021-03-23 14:42
If @ritish099 feature is accepted then we can do one think on single click it will be off and on long click it will show the meaning.
For now I will implement toast on single click.

**Comment by ritish099** [comment] 2021-03-25 04:54
@Bhavya-22 cooool ☺

**Comment by asaikarthikeya** [comment] 2021-07-22 07:34
This issue proposed 2 features 
1. Onclick when red colour is resolved by #762 
2. In my opinion it is too much of information. I feel blue-red colour combination is sufficient to understand whether Bluetooth is on/off. @SebaDro sir, if you feel that on long click feature to be useful then i will implement that or else we can close this PR. Thank you ;)

**Comment by SebaDro** [comment] 2021-07-22 10:15
The red/blue combination should be clear enough for indicating the button state. In addition, the icons are self speaking. Therefore, there is no need for a long click feature. Since #762 solves parts of this issue, it can be considered as done.

**Comment by SebaDro** [comment] 2021-07-23 14:44
Duplicate of #611. I wil close it for now but feel free to open it again, if there is still a valid issue.

**Closed by SebaDro** 2021-07-23 14:44 UTC
Labels: 3 - Done, Priority - 3 - Low, enhancement
