### ISSUE TITLE
[UI-BUG]Car details form is transparent.

### ISSUE THREAD

**Issue by Piyusinha** [enviroCar/enviroCar-app#493] opened 2020-03-10 08:03 UTC
The form of entering car details is empty when you randomly click on it then it will highlight the input box.
![Screenshot_20200310-132113](https://user-images.githubusercontent.com/40850657/76291683-9ffcfc80-62d3-11ea-8a89-7e6c4076dc9d.jpg)
![Screenshot_20200310-132107](https://user-images.githubusercontent.com/40850657/76291690-a1c6c000-62d3-11ea-8797-1591ee154972.jpg)

**Comment by arvindnegi1** [comment] 2020-03-10 09:24
not able to reproduce

**Comment by Piyusinha** [comment] 2020-03-10 14:08
@arvindnegi1 not able to reproduce means?

**Comment by asaikarthikeya** [comment] 2021-06-30 11:11
Unable to reproduce.

**Comment by SebaDro** [comment] 2021-07-02 08:49
Since reproducing the issue is not possible, I will close it. Feel free to open it again, but please, describe the preconditions that cause this issue.

**Closed by SebaDro** 2021-07-02 08:49 UTC
