### ISSUE TITLE
Fix: Unnecessary Floating button blocking the input in add car window

### ISSUE THREAD

**Issue by ritish099** [enviroCar/enviroCar-app#622] opened 2021-03-18 15:27 UTC
**Issue**
Unnecessary and non-Functional Floating button blocking the input in add car window.

**Solution**
Remove the Unnecessary and non-Functional Floating button

**Screenshot**
<img src="https://user-images.githubusercontent.com/54978105/111651787-8bc7d580-882c-11eb-9f82-d92ca6ddc6dd.jpg" width="333">

**Comment by ritish099** [comment] 2021-03-18 15:28
I will be working on this

**Comment by arvindnegi1** [comment] 2021-03-21 15:55
@ritish099 this whole view has been changed in gsoc2020, the branch has not been merged into develop yet.

**Comment by SebaDro** [comment] 2021-07-01 07:26
FAB is still blocking the construction year input, when you try to open the dropdown list by clicking on the arrow for the first time. Any ideas on it @arvindnegi1?

Screenshot:
<img src="https://user-images.githubusercontent.com/18207870/124083123-cbb66f80-da4d-11eb-99e5-b5fc37a4b21e.jpg" width="300">

**Comment by asaikarthikeya** [comment] 2021-07-01 07:35
![Screenshot_20210701-130147_enviroCar](https://user-images.githubusercontent.com/70392921/124084827-04b20c80-da6d-11eb-8110-846a86c7846e.jpg)

**Comment by asaikarthikeya** [comment] 2021-07-01 07:38
@SebaDro I am not able to reproduce this sir. However i will make a PR now. Not sure but this may resolve this. You can check it once.

![Screenshot_20210701-130147_enviroCar](https://user-images.githubusercontent.com/70392921/124084859-0e3b7480-da6d-11eb-97dc-6fae9ba94f96.jpg)

**Comment by arvindnegi1** [comment] 2021-07-01 09:53
@SebaDro  sorry sir i am not able to reproduce this. It can be because after the animation hide the FAB it still shown up in some devices. @asaikarthikeya  has created PR for this.

**Comment by SebaDro** [comment] 2021-07-01 10:33
Unfortunately, it does not fix the issue. In one of the two fragments (HSN/TSN or Attributes), click in the empty area where the FAB was located. This will let the FAB pop up again:

https://user-images.githubusercontent.com/18207870/124110299-5dcb7180-da68-11eb-8ad6-b7e2585c5cec.mp4

**Comment by SebaDro** [comment] 2021-07-01 10:37
>It can be because after the animation hide the FAB it still shown up in some devices.

Ok, that can be the reason, why it won't arise on your device. Any chance to fix this behaviour?

**Comment by SebaDro** [comment] 2021-09-27 07:51
Fixed by #830

**Closed** 2021-11-15 11:51 UTC
Labels: bug, 3 - Done, Priority - 3 - Low
